
Details_StreamerDB = {
["characters"] = {
["Filibaba - Pyrewood Village"] = "Ostreicher - Firemaw",
["Wunderful - Firemaw"] = "Ostreicher - Firemaw",
["Jonaspik - Firemaw"] = "Ostreicher - Firemaw",
["Aiwa - Firemaw"] = "Ostreicher - Firemaw",
["Ostreicher - Firemaw"] = "Ostreicher - Firemaw",
["Estaup - Firemaw"] = "Ostreicher - Firemaw",
["Yuseph - Firemaw"] = "Ostreicher - Firemaw",
["Kodun - Firemaw"] = "Ostreicher - Firemaw",
["Inputs - Firemaw"] = "Ostreicher - Firemaw",
},
["profiles"] = {
["Ostreicher - Firemaw"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["arrow_anchor_y"] = 0,
["main_frame_size"] = {
300,
500.0000305175781,
},
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = false,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["use_spark"] = true,
["author"] = "Terciob",
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["y"] = 7.62939453125e-06,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["font_size"] = 10,
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 0,
["x"] = 0.000335693359375,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["x"] = 0,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["point"] = "CENTER",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["scale"] = 1,
},
},
}
