
GargulDB = {
	["TMB"] = {
	},
	["BoostedRolls"] = {
		["Aliases"] = {
		},
		["Points"] = {
		},
	},
	["LoadDetails"] = {
		["lastLoadedOn"] = 1720619345,
		["7.4.6"] = 1713887050,
		["7.5.3"] = 1719435848,
		["5.1.1"] = 1713887050,
		["7.4.7"] = 1713964738,
		["5.2.0"] = 1713887050,
		["7.4.4"] = 1713199683,
	},
	["LootPriority"] = {
	},
	["GDKP"] = {
		["SettingsPerItem"] = {
		},
		["Queue"] = {
		},
	},
	["AwardHistory"] = {
		["47232556061749724100"] = {
			["checksum"] = "47232556061749724100",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713297499,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["29434123556174972410"] = {
			["checksum"] = "29434123556174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713298680,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["14271135498089312460"] = {
			["checksum"] = "14271135498089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714331203,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["17158155038089312460"] = {
			["checksum"] = "17158155038089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50625,
			["itemLink"] = "|cffa335ee|Hitem:50625::::::::80:::::::::|h[Grinning Skull Greatboots]|h|r",
			["timestamp"] = 1714333100,
			["PL"] = false,
			["GDKPCost"] = 5000,
			["received"] = true,
		},
		["31346303161749724100"] = {
			["checksum"] = "31346303161749724100",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713293173,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["80305431480893124600"] = {
			["checksum"] = "80305431480893124600",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714332882,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["12212826238089312460"] = {
			["checksum"] = "12212826238089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714330304,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["16421874788089312460"] = {
			["checksum"] = "16421874788089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714332383,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["29104819046174972410"] = {
			["checksum"] = "29104819046174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713294122,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["35498821701738482804"] = {
			["checksum"] = "35498821701738482804",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Sickdanni-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50693,
			["itemLink"] = "|cffa335ee|Hitem:50693::::::::80:::::::::|h[Might of Blight]|h|r",
			["timestamp"] = 1713296474,
			["PL"] = false,
			["GDKPCost"] = 5000,
			["received"] = true,
		},
		["54805816180893124600"] = {
			["checksum"] = "54805816180893124600",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714328482,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["17857849598089312460"] = {
			["checksum"] = "17857849598089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714330765,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["23719288438089312460"] = {
			["checksum"] = "23719288438089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714333604,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["23342609542770365010"] = {
			["checksum"] = "23342609542770365010",
			["Rolls"] = {
			},
			["OS"] = false,
			["WL"] = false,
			["winnerClass"] = 8,
			["awardedBy"] = "Josipbroz-Firemaw",
			["SR"] = false,
			["awardedTo"] = "Deepfoxxz-Firemaw",
			["itemLink"] = "|cffa335ee|Hitem:52722::::::::85:::::::::|h[Maelstrom Crystal]|h|r",
			["itemID"] = 52722,
			["PL"] = false,
			["TMB"] = false,
			["timestamp"] = 1719444500,
			["GDKPCost"] = 34000,
			["received"] = true,
		},
		["17501486478089312460"] = {
			["checksum"] = "17501486478089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714329629,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["20815363758089312460"] = {
			["checksum"] = "20815363758089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714328088,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["11682930636174972410"] = {
			["checksum"] = "11682930636174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713296359,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["34765708438089312460"] = {
			["checksum"] = "34765708438089312460",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714329173,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["41533930061749724100"] = {
			["checksum"] = "41533930061749724100",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713295269,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["31666207486174972410"] = {
			["checksum"] = "31666207486174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713295676,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["26753942180893124600"] = {
			["checksum"] = "26753942180893124600",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714336478,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["11215672306174972410"] = {
			["checksum"] = "11215672306174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713294664,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["35850298973811610580"] = {
			["checksum"] = "35850298973811610580",
			["Rolls"] = {
			},
			["OS"] = false,
			["WL"] = false,
			["winnerClass"] = 11,
			["awardedBy"] = "Josipbroz-Firemaw",
			["SR"] = false,
			["awardedTo"] = "Firsteverdr-Firemaw",
			["itemLink"] = "|cffa335ee|Hitem:67426::::::::85:::::::::|h[Leggings of the Forlorn Vanquisher]|h|r",
			["itemID"] = 67426,
			["PL"] = false,
			["TMB"] = false,
			["timestamp"] = 1719435919,
			["GDKPCost"] = 48000,
			["received"] = true,
		},
		["29088027223006447640"] = {
			["checksum"] = "29088027223006447640",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Overloader-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 52029,
			["itemLink"] = "|cffa335ee|Hitem:52029::::::::80:::::::::|h[Protector's Mark of Sanctification]|h|r",
			["timestamp"] = 1714336683,
			["PL"] = false,
			["GDKPCost"] = 10000,
			["received"] = true,
		},
		["79348240180893124600"] = {
			["checksum"] = "79348240180893124600",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Snowbrax-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1714328821,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["36548809806174972410"] = {
			["checksum"] = "36548809806174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713293722,
			["PL"] = false,
			["GDKPCost"] = 3000,
			["received"] = true,
		},
		["25076863976174972410"] = {
			["checksum"] = "25076863976174972410",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Kanttoridk-Firemaw",
			["awardedBy"] = "Rumpri-Firemaw",
			["itemID"] = 50274,
			["itemLink"] = "|cffff8000|Hitem:50274::::::::80:::::::::|h[Shadowfrost Shard]|h|r",
			["timestamp"] = 1713297991,
			["PL"] = false,
			["GDKPCost"] = 6000,
			["received"] = true,
		},
		["20447879661148060648"] = {
			["checksum"] = "20447879661148060648",
			["OS"] = false,
			["WL"] = false,
			["TMB"] = false,
			["SR"] = false,
			["awardedTo"] = "Ostreicher-Firemaw",
			["awardedBy"] = "Josipbroz-Firemaw",
			["itemID"] = 50818,
			["itemLink"] = "|cffa335ee|Hitem:50818::::::::80:::::::::|h[Invincible's Reins]|h|r",
			["timestamp"] = 1714336596,
			["PL"] = false,
			["GDKPCost"] = 70000,
			["received"] = true,
		},
	},
	["Settings"] = {
		["autoOpenCommandHelp"] = true,
		["PackMule"] = {
			["needWithoutAssist"] = false,
			["autoConfirmSolo"] = false,
			["announceDisenchantedItems"] = true,
			["enabledForGroupLoot"] = false,
			["enabledForMasterLoot"] = false,
			["autoDisableForGroupLoot"] = true,
			["Rules"] = {
			},
			["lootGold"] = true,
			["autoConfirmGroup"] = false,
		},
		["TradeAnnouncements"] = {
			["enchantmentReceived"] = true,
			["alwaysAnnounceEnchantments"] = true,
			["enchantmentGiven"] = true,
			["itemsReceived"] = true,
			["goldReceived"] = true,
			["minimumQualityOfAnnouncedLoot"] = 0,
			["mode"] = "WHEN_MASTERLOOTER",
			["itemsGiven"] = true,
			["goldGiven"] = true,
		},
		["debugModeEnabled"] = false,
		["changeLog"] = true,
		["TMB"] = {
			["OSHasLowerPriority"] = true,
			["maximumNumberOfAnnouncementEntries"] = 5,
			["automaticallyShareData"] = false,
			["showRaidGroup"] = true,
			["announcePriolistInfoWhenRolling"] = true,
			["hideInfoOfPeopleNotInGroup"] = true,
			["includeWishListInfoInLootAnnouncement"] = true,
			["showWishListInfoOnTooltips"] = true,
			["showPrioListInfoOnTooltips"] = true,
			["includePrioListInfoInLootAnnouncement"] = true,
			["showItemInfoOnTooltips"] = true,
			["announceWishlistInfoWhenRolling"] = true,
			["maximumNumberOfTooltipEntries"] = 35,
			["showEntriesWhenUsingPrio3"] = true,
			["shareWhitelist"] = "",
			["showEntriesWhenSolo"] = true,
			["hideWishListInfoIfPriorityIsPresent"] = true,
		},
		["GDKP"] = {
			["whisperGoldDetails"] = true,
			["closeAuctioneerOnAward"] = false,
			["auctionEndLeeway"] = 2,
			["minimizeAuctioneerOnStart"] = true,
			["announceBidsClosed"] = true,
			["announceNewBid"] = true,
			["customExportHeader"] = "Item,Player,Gold,Wowheadlink",
			["exportFormat"] = 1,
			["addBOEDropsToQueue"] = true,
			["minimumDropQuality"] = 4,
			["acceptBidsLowerThanMinimum"] = false,
			["announcePotAfterAuction"] = true,
			["announceCountdownInRW"] = true,
			["ItemLevelDetails"] = {
			},
			["numberOfSecondsToCountdown"] = 5,
			["showQueueWindow"] = true,
			["customPotExportFormat"] = "@PLAYER,@CUT",
			["announceFinalCall"] = true,
			["antiSnipe"] = 15,
			["enableBidderQueue"] = true,
			["announceNewBidInRW"] = true,
			["MultiAuction"] = {
				["Filters"] = {
				},
				["minimumFillQuality"] = 4,
				["time"] = 600,
				["includeMaterials"] = false,
				["awardNotice"] = true,
				["includeAwarded"] = false,
				["antiSnipe"] = 15,
				["includeBOEs"] = true,
			},
			["finalCallTime"] = 10,
			["showBidWindow"] = true,
			["queueIsHalted"] = true,
			["storeMinimumAndIncrementPerItem"] = true,
			["showHistoryOnTooltip"] = true,
			["time"] = 30,
			["bidderQueueHideUnusable"] = false,
			["invalidBidsTriggerAntiSnipe"] = true,
			["precision"] = 0,
			["outbidSound"] = "Gargul: uh-oh",
			["numberOfFiveSecondsToCountdown"] = 15,
			["notifyIfBidTooLow"] = true,
			["bidderScale"] = 1,
			["ledgerAuctionScale"] = 30,
			["customPotExportHeader"] = "Player,Cut",
			["defaultIncrement"] = 100,
			["potExportFormat"] = 1,
			["customExportFormat"] = "@ITEM,@WINNER,@GOLD,@WOWHEAD",
			["SettingsPerItem"] = {
			},
			["announceAuctionStart"] = true,
			["disableQueues"] = false,
			["autoAwardViaAuctioneer"] = true,
			["defaultMinimumBid"] = 500,
			["delayBetweenQueuedAuctions"] = 1,
			["addGoldToTradeWindow"] = true,
			["queuedAuctionNoBidsAction"] = "SKIP",
			["addDropsToQueue"] = true,
		},
		["ExportingLoot"] = {
			["disenchanterIdentifier"] = "_disenchanted",
			["customFormat"] = "@ID;@DATE @TIME;@WINNER",
			["includeDisenchantedItems"] = true,
			["format"] = 1,
			["showLootAssignmentReminder"] = true,
			["includeOffspecItems"] = true,
		},
		["UI"] = {
			["PopupDialog"] = {
				["Position"] = {
					["point"] = "TOP",
					["offsetY"] = -115,
					["offsetX"] = 0,
					["relativePoint"] = "TOP",
				},
			},
			["RollOff"] = {
				["timer"] = 30,
				["closeOnStart"] = false,
				["closeOnAward"] = false,
			},
			["ReopenAuctioneerButton"] = {
				["offsetX"] = 188,
				["relativePoint"] = "CENTER",
				["offsetY"] = -5.5,
				["point"] = "CENTER",
				["Position"] = {
					["point"] = "CENTER",
					["offsetY"] = -5.5,
					["offsetX"] = 188,
					["relativePoint"] = "CENTER",
				},
			},
			["Settings"] = {
				["Position"] = {
					["offsetX"] = 0,
					["offsetY"] = 0,
					["point"] = "CENTER",
					["relativePoint"] = "CENTER",
				},
			},
			["Award"] = {
				["closeOnAward"] = true,
			},
			["Gargul"] = {
				["BidderQueue"] = {
					["Window"] = {
						["Position"] = {
							["offsetX"] = 0,
							["offsetY"] = -2.593649514892604e-05,
							["point"] = "CENTER",
							["relativePoint"] = "CENTER",
						},
						["Dimensions"] = {
							["height"] = 170,
							["scale"] = 1,
							["width"] = 150.0001373291016,
						},
					},
				},
			},
		},
		["PlusOnes"] = {
			["automaticallyShareData"] = false,
			["enableWhisperCommand"] = true,
			["blockShareData"] = false,
			["automaticallyAcceptDataFrom"] = "",
		},
		["fontSize"] = 11,
		["ShortcutKeys"] = {
			["disenchant"] = "CTRL_SHIFT_CLICK",
			["rollOff"] = "DISABLED",
			["award"] = "ALT_SHIFT_CLICK",
			["showLegend"] = true,
			["auction"] = "DISABLED",
			["disableWhenCLMIsActive"] = false,
			["doubleClickToTrade"] = true,
			["rollOffOrAuction"] = "ALT_CLICK",
			["onlyInGroup"] = false,
		},
		["noMessages"] = false,
		["BoostedRolls"] = {
			["defaultPoints"] = 100,
			["fixedRolls"] = false,
			["defaultStep"] = 10,
			["automaticallyShareData"] = true,
			["reserveThreshold"] = 180,
			["enableWhisperCommand"] = true,
			["identifier"] = "BR",
			["defaultCost"] = 10,
			["priority"] = 1,
			["enabled"] = false,
			["automaticallyAcceptDataFrom"] = "",
		},
		["highlightMyItemsOnly"] = false,
		["highlightPriolistedItems"] = true,
		["noSounds"] = false,
		["DroppedLoot"] = {
			["minimumQualityOfLoggedLoot"] = 4,
			["announceDroppedLootInRW"] = false,
			["announceLootToChat"] = true,
			["minimumQualityOfAnnouncedLoot"] = 4,
		},
		["RollTracking"] = {
			["sortByTMBWishlist"] = true,
			["rollOffEndLeeway"] = 1,
			["sortByTMBPrio"] = true,
			["trackAll"] = false,
			["sortBySoftRes"] = true,
			["Brackets"] = {
				{
					"MS", -- [1]
					1, -- [2]
					100, -- [3]
					2, -- [4]
					false, -- [5]
					false, -- [6]
				}, -- [1]
				{
					"OS", -- [1]
					1, -- [2]
					99, -- [3]
					3, -- [4]
					true, -- [5]
					false, -- [6]
				}, -- [2]
			},
		},
		["LootTradeTimers"] = {
			["enabled"] = true,
			["Broadcast"] = {
				["includeTimeLeft"] = true,
				["numberOfItems"] = 20,
				["minimumQuality"] = 4,
				["includeHiddenItems"] = false,
				["includeAwardedItems"] = false,
				["channel"] = 1,
				["includeDisenchantedItems"] = false,
				["maximumTradeTimeLeft"] = 120,
			},
			["scale"] = 1,
			["hideAwarded"] = false,
			["showHotkeyReminder"] = true,
			["showOnlyWhenMasterLooting"] = true,
			["maximumTradeTimeLeft"] = 120,
			["maximumNumberOfBars"] = 5,
			["hideDisenchanted"] = false,
			["hideAwardedToSelf"] = false,
		},
		["showUpdateAlert"] = false,
		["profilerEnabled"] = false,
		["welcomeMessage"] = true,
		["MinimapButton"] = {
			["enabled"] = true,
			["Actions"] = {
				["CTRL_MIDDLECLICK"] = "DISABLED",
				["ALT_RIGHTCLICK"] = "DISABLED",
				["RIGHTCLICK"] = "IMPORT",
				["CTRL_SHIFT_RIGHTCLICK"] = "DISABLED",
				["SHIFT_RIGHTCLICK"] = "EXPORT",
				["CTRL_RIGHTCLICK"] = "DISABLED",
				["ALT_CLICK"] = "DISABLED",
				["MIDDLECLICK"] = "AWARDHISTORY",
				["SHIFT_MIDDLECLICK"] = "DISABLED",
				["ALT_SHIFT_CLICK"] = "DISABLED",
				["SHIFT_CLICK"] = "SOFTRES",
				["ALT_MIDDLECLICK"] = "DISABLED",
				["CTRL_SHIFT_MIDDLECLICK"] = "DISABLED",
				["CTRL_SHIFT_CLICK"] = "DISABLED",
				["ALT_SHIFT_MIDDLECLICK"] = "DISABLED",
				["CLICK"] = "GARGUL",
				["ALT_SHIFT_RIGHTCLICK"] = "DISABLED",
				["CTRL_CLICK"] = "DISABLED",
			},
		},
		["highlightsEnabled"] = true,
		["soundChannel"] = "SFX",
		["highlightWishlistedItems"] = true,
		["Rolling"] = {
			["showRollOffWindow"] = true,
			["closeAfterRoll"] = false,
			["scale"] = 1,
		},
		["highlightSoftReservedItems"] = true,
		["highlightHardReservedItems"] = true,
		["MasterLooting"] = {
			["announceCountdownOnce"] = false,
			["preferredMasterLootingThreshold"] = 2,
			["announceRollEnd"] = true,
			["numberOfSecondsToCountdown"] = 5,
			["doCountdown"] = true,
			["autoOpenMasterLooterDialog"] = true,
			["linkNormalAndHardModeItems"] = false,
			["announceRollStart"] = true,
			["alwaysUseDefaultNote"] = false,
			["announceMasterLooter"] = false,
			["defaultRollOffNote"] = "/roll for MS or /roll 99 for OS",
		},
		["AwardingLoot"] = {
			["announceAwardMessagesInGuildChat"] = false,
			["autoTradeDisenchanter"] = true,
			["autoTradeInCombat"] = true,
			["awardOnReceive"] = false,
			["announceAwardMessagesInRW"] = false,
			["autoAssignAfterAwardingAnItem"] = true,
			["awardMessagesEnabled"] = true,
			["autoTradeAfterAwardingAnItem"] = true,
			["awardOnReceiveMinimumQuality"] = 4,
			["skipAwardConfirmationDialog"] = false,
			["notifyOfFailedTradeStart"] = true,
		},
		["SoftRes"] = {
			["enableWhisperCommand"] = true,
			["announceInfoWhenRolling"] = true,
			["announceInfoInChat"] = true,
			["enableTooltips"] = true,
			["fixPlayerNames"] = true,
			["hideInfoOfPeopleNotInGroup"] = true,
		},
	},
	["SoftRes"] = {
	},
	["RecentlyAwardedItems"] = {
	},
	["PlusOnes"] = {
		["Totals"] = {
		},
	},
	["MinimapButton"] = {
	},
	["Utility"] = {
	},
}
